# Generated by Django 3.1.3 on 2020-12-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201215_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
