# Generated by Django 3.1.3 on 2020-12-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201215_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-created_on']},
        ),
    ]
