# Generated by Django 3.1.3 on 2020-12-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201216_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
