# Generated by Django 3.1.3 on 2020-12-05 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name_plural': 'Contact Form Submissions'},
        ),
        migrations.AddField(
            model_name='contactform',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactform',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
