from django.test import SimpleTestCase
from django.urls import reverse, resolve
from .views import HomePageView
from . import views


class SimpleTests(SimpleTestCase):
    def test_home_page_status_code(self):
        response = self.client.get('/')
        self.assertEqual(response.status_code, 200)

    def test_home_page_url_resolves_home_page_view(self):
        # class-based views need to be compared by name, as the functions
        # generated by as_view() won't be equal
        view = resolve('/')
        self.assertEquals(
            view.func.__name__,
            views.HomePageView.as_view().__name__
            )

    def test_contact_page_status_code(self):
        response = self.client.get('/contact/')
        self.assertEqual(response.status_code, 200)
